package io.memris.runtime;

/**
 * Interface for entity save operations with zero reflection.
 * <p>
 * Implementations of this interface are generated by ByteBuddy with direct
 * field access for entity value extraction.
 * Relationship ID extraction uses precomputed accessors initialized at
 * generation time.
 *
 * @param <T> the entity type
 * @param <I> the ID type
 */
public interface EntitySaver<T, I> {

    /**
     * Save an entity to the table.
     * <p>
     * Implementations use direct field access to extract values from the entity
     * and call table.insertFrom() with the values array.
     *
     * @param entity the entity to save
     * @param table  the generated table
     * @param id     the entity ID (already generated if needed)
     * @return the saved entity (same instance, possibly modified with ID)
     */
    T save(T entity, io.memris.storage.GeneratedTable table, I id);

    /**
     * Extract the ID from an entity.
     * <p>
     * Uses direct field access to get the ID value.
     *
     * @param entity the entity
     * @return the ID value, or null if not set
     */
    I extractId(T entity);

    /**
     * Set the ID on an entity.
     * <p>
     * Uses direct field access to set the ID value.
     *
     * @param entity the entity
     * @param id     the ID to set
     */
    void setId(T entity, I id);

    /**
     * Resolve the ID from a related entity for relationship fields.
     * <p>
     * For @ManyToOne/@OneToOne fields, extracts the ID from the related entity.
     *
     * @param fieldName     the relationship field name
     * @param relatedEntity the related entity object
     * @return the ID value of the related entity, or null
     */
    Object resolveRelationshipId(String fieldName, Object relatedEntity);
}
