package io.memris.spring;

import io.memris.spring.converter.TypeConverter;
import io.memris.storage.ffm.FfmTable;

import java.lang.invoke.MethodHandle;
import java.lang.reflect.Constructor;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Metadata captured at repository creation time.
 * All reflection work happens once, then this metadata
 * is used by generated bytecode for zero-overhead access.
 */
public final class EntityMetadata<T> {
    final Class<T> entityClass;
    final Constructor<T> entityConstructor;
    final String idColumnName;
    final List<FieldMapping> fields;
    final Set<String> foreignKeyColumns;

    // NEW: Pre-compiled TypeConverters per field
    final Map<String, TypeConverter<?, ?>> converters;

    // NEW: Pre-compiled lifecycle callback MethodHandles
    final MethodHandle prePersistHandle;
    final MethodHandle postLoadHandle;
    final MethodHandle preUpdateHandle;

    public EntityMetadata(
            Class<T> entityClass,
            Constructor<T> entityConstructor,
            String idColumnName,
            List<FieldMapping> fields,
            Set<String> foreignKeyColumns,
            Map<String, TypeConverter<?, ?>> converters,
            MethodHandle prePersistHandle,
            MethodHandle postLoadHandle,
            MethodHandle preUpdateHandle) {
        this.entityClass = entityClass;
        this.idColumnName = idColumnName;
        this.entityConstructor = entityConstructor;
        this.fields = fields;
        this.foreignKeyColumns = foreignKeyColumns;
        this.converters = converters;
        this.prePersistHandle = prePersistHandle;
        this.postLoadHandle = postLoadHandle;
        this.preUpdateHandle = preUpdateHandle;
    }

    public Class<T> entityClass() {
        return entityClass;
    }

    public String idColumnName() {
        return idColumnName;
    }

    public Constructor<T> entityConstructor() {
        return entityConstructor;
    }

    public List<FieldMapping> fields() {
        return fields;
    }

    public Set<String> foreignKeyColumns() {
        return foreignKeyColumns;
    }

    public Map<String, TypeConverter<?, ?>> converters() {
        return converters;
    }

    public MethodHandle prePersistHandle() {
        return prePersistHandle;
    }

    public MethodHandle postLoadHandle() {
        return postLoadHandle;
    }

    public MethodHandle preUpdateHandle() {
        return preUpdateHandle;
    }

    /**
     * Mapping between entity field and table column.
     * Used to generate direct field access in bytecode.
     */
    public record FieldMapping(
            String name,           // Field name (e.g., "price")
            String columnName,     // Column name (e.g., "price")
            Class<?> javaType,     // Field type (e.g., int.class)
            Class<?> storageType,  // Storage type (e.g., int.class)
            int columnPosition     // Column index in table (for potential optimization)
    ) {}
}
