package io.memris.spring;

/**
 * Type code constants for zero-overhead type switching.
 * Pre-computed at metadata extraction time, used in generated bytecode.
 */
public final class TypeCodes {
    private TypeCodes() {
        // Utility class - no instances
    }

    public static final int TYPE_INT = 0;
    public static final int TYPE_LONG = 1;
    public static final int TYPE_BOOLEAN = 2;
    public static final int TYPE_BYTE = 3;
    public static final int TYPE_SHORT = 4;
    public static final int TYPE_FLOAT = 5;
    public static final int TYPE_DOUBLE = 6;
    public static final int TYPE_CHAR = 7;
    public static final int TYPE_STRING = 8;
}
